### ISSUE TITLE
Otimização de uso do Plugin Google Docs for Figma

### ISSUE THREAD

**Issue by uira** [DesignLabAPS/devLab#1]

**Comment by vicmagpac** [comment]
No momento o processo de teste está sendo realizado dentro de uma cópia da planilha e cópia do artefato do figma para realizar alguns testes e mudança de styles. 

Exemplo do estilo que está sendo aplicado para cada componente (coluna) da planilha: 
![image](https://github.com/DesignLabAPS/devLab/assets/3487411/f60823cf-5b3c-4646-8754-98ebd44ffc6e)

Em análise, verificamos que é necessário uma conversa e análise para definirmos o padrão da planilha, abas e definição de estilos por "status", "equipe", "Posição" e etc.
